name: my CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Debug Build with Gradle
      run: ./gradlew assembleDebug

  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run unit-test
      run: ./gradlew testDebugUnitTest
    - name: unit-test result
      uses: actions/upload-artifact@v2
      with:
        name: unit-test result
        path: ~/**/build/reports/tests/testDebugUnitTest/index.html
      
  gen-apk:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Upload APK 
      uses: actions/upload-artifact@v2
      with:
          name: app
          path: app/build/outputs/apk/debug
   
